### ISSUE TITLE
Proposed adjustments to page diff CSS

### ISSUE THREAD

**Issue by egocarib** [TrashMonks/Vector#2]
Some minor adjustments that we could make to improve page history diffing colors. (Note I haven't looked at the vector stuff in detail, so there might be a neater way to merge this into existing vector CSS, rather than layering it over the top - but this is a starting point at least):

```css
	td.diff-context {
		background-color: #222722;
		border: none;
		color: var(--body-color);
	}
	td.diff-deletedline {
		background-color: #500000;
		border: none
	}
	td.diff-addedline {
		background-color: #004000;
		border: none;
	}
	td.diff-deletedline .diffchange {
		background: #6f0606;
		color: #ff5151
	}
	td.diff-addedline .diffchange {
		background: #20560e;
		color: #d5f752;
	}
```

Adding this to the page results in a diff that looks like the following. Much more similar to old wiki diffs (but not copied directly from there)

![image](https://user-images.githubusercontent.com/3429497/129256084-717e2e30-9d2a-4125-b1b6-f1e647530e46.png)

For context, the current diff looks like this right now:

![image](https://user-images.githubusercontent.com/3429497/129256272-26956073-2247-4b04-a896-6e6e744b0ff7.png)
